### ISSUE TITLE
[Question] Does the data include the link flair labels? (css: linkflairlabel)

### ISSUE THREAD

**Issue by rntsn** [dewarim/reddit-data-tools#2]
E.g. "Ad" on some /r/videos links.
Not sure if this is the appropriate place for this question.

I see the field author_flair_text on pushshift's submission table: https://pushshift.io/wp-content/uploads/2016/02/pushshift_submissions.png, but I imagine that is the author's flair and not the submission's flair.

**Comment by dewarim** [comment]
No, I think this is only available for submissions, not comments like the linked torrents.
https://files.pushshift.io/reddit/submissions/ vs https://files.pushshift.io/reddit/comments

... guess I should make a collection of submissions, too ;)

Submissions do in fact have this flag:
    {"downs":1093,"link_flair_text":"Editorialized Title",

But mostly it's "null".

**Comment by rntsn** [comment]
Ah, exactly what I was looking for, thanks.
And yes, that would be very helpful :)
